package com.acg.mangalive.catalog.domain.model

enum class SortingCriterionFilter {
    ByPopularity,
    ByRating,
    ByViews,
    ByUpdates,
    ByNovelty,
    ByChaptersNumber;

    companion object {
        const val DEFAULT_ITEM_INDEX = 0

        val defaultItem
            get() = values()[DEFAULT_ITEM_INDEX]
    }
}

enum class TypeFilter {
    Manga,
    Manhva,
    Manhua,
    WestComic,
    RussianComic,
    IndonesianComic,
    Other,
}

enum class GenreFilter {
    Action,
    ActionsArts,
    Harem,
    GenderIntrigue,
    HeroicFantasy,
    Detective,
    Josei,
    Doijishi,
    Drama,
    Game,
    Story,
    Cyberpunk,
    Kodomo,
    Comedy,
    MachoShojo,
    Mecha,
    Mystic,
    Murim,
    ScienceFantasy,
    Everyday,
    Postapocalyptic,
    Adventures,
    Psychology,
    Romance,
    Supernatural,
    Shoujo,
    Shonen,
    Sports,
    Seinen,
    Tragedy,
    Thriller,
    Horror,
    Fantasy,
    School,
    ElementsOfHumor,
    Erotica,
    Ethics,
    Yuri,
    Yaoi,
}

enum class CategoryFilter {
    Alchemy,
    Angels,
    Antihero,
    Dystopia,
    Apocalypse,
    Aristocracy,
    Army,
    Artifacts,
    Gods,
    SwordFighting,
    StruggleForPower,
    Future,
    InColor,
    Vampires,
    Web,
    Western,
    VideoGames,
    VirtualReality,
    DemonLord,
    Military,
    MagicalCreatures,
    MemoriesFromAnotherWorld,
    Survival,
    GgWoman,
    GgImba,
    GgMale,
    GgIsNotHuman,
    Gamers,
    Guilds,
    Goblins,
    Maids,
    Gyaru,
    MonsterGirls,
    Demons,
    Dragons,
    Friendship,
    Yonkoma,
    CruelWorld,
    AnimalCompanions,
    ConquestOfTheWorld,
    Beastmen,
    Zombies,
    GameElements,
    Isekai,
    Quests,
    Space,
    Cooking,
    Cultivation,
    Loli,
    MagicAcademy,
    Magic,
    Mafia,
    Medicine,
    Revenge,
    Monsters,
    Music,
    Mercenaries,
    Undead,
    Ninja,
    Werewolves,
    ReverseHarem,
    OfficeWorkers,
    Parody,
    Dungeons,
    Policy,
    Police,
    Leveling,
    Trash,
    TimeTravel,
    SentientRaces,
    PowerRanks,
    Reincarnation,
    Robots,
    Knights,
    Samurai,
    Collection,
    Single,
    System,
    IdentityHiding,
    SavingTheWorld,
    MiddleAges,
    Steampunk,
    Superheroes,
    TraditionalGames,
    StupidGg,
    SmartGg,
    TerritoryManagement,
    Philosophy,
    Hentai,
    Hikikomori,
    Blackmail,
    Elves,
}

data class SelectedFilters(
    val sortingCriterion: SortingCriterionFilter = SortingCriterionFilter.defaultItem,
    val types: List<TypeFilter> = listOf(),
    val genres: List<GenreFilter> = listOf(),
    val categories: List<CategoryFilter> = listOf(),
)
